### ISSUE TITLE
Playnite's fullscreen mode won't launch/Crashed

### ISSUE THREAD

**Issue by RONTVHD** [saVantCZ/DashX#1]
Playnite's fullscreen mode won't launch or crashed after i switch to this theme.

**Comment by saVantCZ** [comment]
Some users reports same thing, they were using unreleased version i have send to discord.

If thats the case, remove unreleased version called "XBOXafterbirth" and reinstall theme.

If thats not a case, i would need log of crash happening. Inside playnite folder there should be playnite.log file, you can send it with last entry being crash.

**Comment by racerlucas** [comment]
> Some users reports same thing, they were using unreleased version i have send to discord.
> 
> If thats the case, remove unreleased version called "XBOXafterbirth" and reinstall theme.
> 
> If thats not a case, i would need log of crash happening. Inside playnite folder there should be playnite.log file, you can send it with last entry being crash.

Same here, log showing
Playnite.FullscreenApp.Windows.MainWindowFactory: 4e1da439-ae74-4259-8988-95f691e4165a
12-05 15:03:45.378|ERROR|ImageSourceManager:Failed to get bitmap from ...\ExtraMetadata\Themes\Common\ProfilePicture.png database file.
System.Exception: Database is not opened.

**Comment by saVantCZ** [comment]
Try opening another or default fullscreen theme, go to settings and enable horizontal scrolling, then launch dashx

**Comment by Gajaa05** [comment]
I have the same problem after i changed the constant file

**Comment by ElTioRata** [comment]
Enabling horizontal scrolling fixed it for me.

**Comment by ElTioRata** [comment]
As of latest update (v2.0.0), looks like the crash has been fixed for me.
